### ISSUE TITLE
Can't import products on clean install

### ISSUE THREAD

**Issue by sunscreem** [statamic-rad-pack/shopify#258]
### Description

Hey Ryan,

Sorry about this - not sure if this one is on me:

```
================================================================
Fetching data for product 9648212541788

   Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException 

  The file "" does not exist

  at vendor/symfony/http-foundation/File/File.php:36
     32▕      */
     33▕     public function __construct(string $path, bool $checkPath = true)
     34▕     {
     35▕         if ($checkPath && !is_file($path)) {
  ➜  36▕             throw new FileNotFoundException($path);
     37▕         }
     38▕ 
     39▕         parent::__construct($path);
     40▕     }

      +40 vendor frames 

  41  artisan:13
      Illuminate\Foundation\Application::handleCommand()
 ```
 
 This comes up when I'm importing a product - I've double checked the docs and maybe I missed a step in the config setup?

### Steps to reproduce

As with previous issue - clean install.

### Environment

Environment
Application Name: Statamic
Laravel Version: 11.31.0
PHP Version: 8.3.9
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: test.robertcooper.xyz
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.37.0 Solo

Statamic Addons
statamic-rad-pack/shopify: 5.0.3

**Comment by ryanmitchell** [comment]
Can you provide the complete error trace from your logs?

**Comment by sunscreem** [comment]
Sure :)

```
[2024-11-22 10:48:27] local.ERROR: The file "" does not exist {"exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"\" does not exist at /home/forge/test.robertcooper.xyz/vendor/symfony/http-foundation/File/File.php:36)
[stacktrace]
#0 /home/forge/test.robertcooper.xyz/vendor/symfony/http-foundation/File/UploadedFile.php(72): Symfony\\Component\\HttpFoundation\\File\\File->__construct()
#1 /home/forge/test.robertcooper.xyz/vendor/statamic-rad-pack/shopify/src/Traits/SavesImagesAndMetafields.php(86): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct()
#2 /home/forge/test.robertcooper.xyz/vendor/statamic-rad-pack/shopify/src/Traits/SavesImagesAndMetafields.php(31): StatamicRadPack\\Shopify\\Jobs\\ImportSingleProductJob->uploadFakeFileFromUrl()
#3 /home/forge/test.robertcooper.xyz/vendor/statamic-rad-pack/shopify/src/Jobs/ImportSingleProductJob.php(98): StatamicRadPack\\Shopify\\Jobs\\ImportSingleProductJob->importImages()
#4 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): StatamicRadPack\\Shopify\\Jobs\\ImportSingleProductJob->handle()
#5 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#9 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#10 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#11 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#13 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#14 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#15 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then()
#17 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#18 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#19 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(76): Illuminate\\Queue\\Jobs\\Job->fire()
#20 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(56): Illuminate\\Queue\\SyncQueue->executeJob()
#21 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(59): Illuminate\\Queue\\SyncQueue->push()
#22 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(247): Illuminate\\Queue\\Queue->pushOn()
#23 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(230): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#24 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#25 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(205): Illuminate\\Bus\\Dispatcher->dispatch()
#26 /home/forge/test.robertcooper.xyz/vendor/statamic-rad-pack/shopify/src/Http/Controllers/Webhooks/ProductCreateUpdateController.php(29): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#27 /home/forge/test.robertcooper.xyz/vendor/statamic-rad-pack/shopify/src/Http/Controllers/Webhooks/ProductCreateUpdateController.php(14): StatamicRadPack\\Shopify\\Http\\Controllers\\Webhooks\\ProductCreateUpdateController->processWebhook()
#28 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): StatamicRadPack\\Shopify\\Http\\Controllers\\Webhooks\\ProductCreateUpdateController->create()
#29 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#30 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#31 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#32 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#33 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#34 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#36 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#38 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#42 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#49 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#51 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#53 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /home/forge/test.robertcooper.xyz/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#56 /home/forge/test.robertcooper.xyz/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#58 /home/forge/test.robertcooper.xyz/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#60 /home/forge/test.robertcooper.xyz/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#62 /home/forge/test.robertcooper.xyz/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#64 /home/forge/test.robertcooper.xyz/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#66 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#68 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#69 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#71 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#72 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#74 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#76 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#78 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#80 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle()
#82 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#84 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#85 /home/forge/test.robertcooper.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle()
#86 /home/forge/test.robertcooper.xyz/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#87 {main}
"} 
```

**Comment by ryanmitchell** [comment]
That will be specific to your install as you have a different local path to the default. The method will need updated to get the path from the storage facade.

**Comment by ryanmitchell** [comment]
@n-va see https://github.com/statamic-rad-pack/shopify/pull/271 - let me know if this works for you

**Comment by n-va** [comment]
Hey @ryanmitchell, that does resolve the issue, thanks!

Running the import brings me to another problem with running the import though. Apparently WEBP images aren't supported as per Statamic's ImageValidator class.

Should I submit this as a separate issue on the repo?

```
[2025-01-16 16:24:36] local.ERROR: Image [shopify/alidavies01.webp] does not actually appear to be a valid image. {"exception":"[object] (Exception(code: 0): Image [shopify/alidavies01.webp] does not actually appear to be a valid image. at /Users/nick/Sites/Project/vendor/statamic/cms/src/Imaging/ImageGenerator.php:309)
[stacktrace]
#0 /Users/nick/Sites/Project/vendor/statamic/cms/src/Imaging/ImageGenerator.php(255): Statamic\\Imaging\\ImageGenerator->validateImage()
```

**Comment by ryanmitchell** [comment]
I believe they are supported as long as the underlying processor (GD, Imagemagick) supports them on your server.
